version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - Test
            - Test2
jobs:
  build:
    docker: 
      - image: alpine:latest
    steps:
      - run: echo $TEST
