version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - Test2
            - Test
jobs:
  build:
    docker: 
      - image: alpine:latest
    steps:
      - run: echo $TEST
